// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj0lE032-jDEXwsMnturd3HiruiZ9wkbI',
    appId: '1:74597899679:android:23d801d97170f52ee5b1aa',
    messagingSenderId: '74597899679',
    projectId: 'veete-68a78',
    databaseURL: 'https://veete-68a78-default-rtdb.firebaseio.com',
    storageBucket: 'veete-68a78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP1-9Zu3s979Njh5bRMwtlxYKOrqQmta0',
    appId: '1:74597899679:ios:8c12d565a509f6c8e5b1aa',
    messagingSenderId: '74597899679',
    projectId: 'veete-68a78',
    databaseURL: 'https://veete-68a78-default-rtdb.firebaseio.com',
    storageBucket: 'veete-68a78.appspot.com',
    iosClientId: '74597899679-urlvemo0ueot73q8jm198o24mf1usej8.apps.googleusercontent.com',
    iosBundleId: 'com.example.veete',
  );
}
